apiVersion: v1
kind: Service
metadata:
  name: api-exemple
  namespace: api
  labels:
    app: api-exemple
spec:
  selector:
    app: api-exemple
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer